### ISSUE TITLE
Evince gets installed to a nonstandard location, and doesn't add that directory to the Path.

### ISSUE THREAD

**Issue by audreytoskin** [aronovgj/chocolatey#2]
I just installed evince 2.32.0.145 from the Chocolatey CLI 0.10.7 on Windows 10 x86_64 Home Edition version 1703, OS Build 15063.332.

Evince gets installed to `C:\users\USERNAME\AppData\Local\Apps` -- but this is not by default part of the user's Path variable, and the Evince script does not add the directory *to* the Path.

I feel like system-wide installations to `Program Files` are better because on a multi-user machine, you don't have to separately install the application for each user, and on a single-user machine, they shouldn't have any trouble running as admin to install the application... But if you're going to do a local install to a nonstandard location, it should at least be added to the Path :)

**Comment by aronovgj** [comment]
Well, that is not me as you can see in the script but it is the default location specified in the msi file. You could try convincing the evince devs to change it... But evince for Windows seems pretty much to be abandonware. For the public repo you should not change the defaults of the installer if you can avoid it. I think this is also in the guidelines. You can override the silent args with your own args if the installer allows it.

I also don't think it is indispensable to have it on Path. I don't like cluttering Path anyway. Why would you want it there?

**Comment by audreytoskin** [comment]
> I don't like cluttering Path anyway. Why would you want it there?

Why would I want an application to be available in the Path? So I can more easily use it, obviously :P

You're right, though: Even when I manually download the installer and run it myself as administrator, it doesn't ask for an installation location... Also, I hadn't noticed that the Windows version of Evince is pretty far behind the Linux version anyway. I'd thought I'd stick with Evince since that's what I use on my Linux machine, but maybe I'll use something else for Windows after all.

Thanks anyway.
