### ISSUE TITLE
[Bug] CCEnhancer Out Of Date

### ISSUE THREAD

**Issue by zero77** [aronovgj/chocolatey#3]
CCEnhancer Is out of date the choco version is 4.5.1 and the newest version is 4.5.4, can you please update CCEnhancer to the newest version.
Thanks

https://chocolatey.org/packages/ccenhancer

**Comment by aronovgj** [comment]
I distrust CCleaner since they essentially became Spyware. Therefore I discontinued the support for CCEnhancer. Sorry for that.

https://www.ghacks.net/2018/08/01/ccleaner-5-45-dont-install/

**Comment by zero77** [comment]
@aronovgj 
Could you move the package to the main repository instead.
Thanks
https://github.com/chocolatey/chocolatey-coreteampackages

**Comment by aronovgj** [comment]
AFAIK coreteampackages has to fork it and it is based on AU while my packages are still automated via Ketarin. Not sure if I can do anything about it. I think someone would have to create the package from scratch.

**Comment by zero77** [comment]
> my packages are still automated via Ketarin. Not sure if I can do anything about it. I think someone would have to create the package from scratch.

Yes, i think you are right.
If you don't want to maintain it any more than could you open an issue on chocolatey-package-requests so, someone else can maintain it.
Thanks

https://github.com/chocolatey/chocolatey-package-requests

**Comment by aronovgj** [comment]
Sure, I'll do it later

**Comment by zero77** [comment]
Thanks

**Comment by aronovgj** [comment]
https://github.com/chocolatey/chocolatey-package-requests/issues/587
